dagstore.go

We now have three "queues":
1. internal: tasks emitted by the event loop, buffer=1.
2. completion: tasks emitted by asynchronous jobs.
3. external: intake of external tasks through public API.
We now drain internal first; then move on to completion and external.

@raulk remove overflow mechanism by segregating channels.

---

dagstore.go
dagstore_control.go
dagstore_test.go
go.mod
go.sum

Implements the `GC()` method outlined in https://github.com/filecoin-project/dagstore/issues/26.
Closes https://github.com/filecoin-project/dagstore/issues/26.

implement DAGStore#GC.

---

dagstore.go
dagstore_async.go
dagstore_control.go
dagstore_test.go
dispatcher.go
mount/counting.go
mount/upgrader_test.go
shard.go
shard_persist.go

Closes #45.
This PR implements lazy initialization. When registering a shard, users can now pass an option:
```go
err := dagst.RegisterShard(context.Background(), k, mount, ch, RegisterOpts{
LazyInitialization: true,
})
```
If `true`, the shard will not be fetched and indexed until its first acquire. The registration callback channel will fire immediately after the control loop has acknowleged the registration.
To support this option, the fetching/indexing logic has been separated out into an `OpShardInitialize` operation.
Lazy init is saved as an attribute in the persistent shard representation, and recovered when restarting.

implement lazy initialization.

---

accessor.go
go.mod
go.sum

This PR changes how we instantiate a CARv2 ReadOnly blockstore by passing in an option that instructs the CARv2 library to safely ignore null padding bytes that are appended at the end of a deal payload by Lotus.
@raulk Please can we cut a 0.2 release after merging this so we can depend on it ?

Update CARv2 lib and use the correct option

---

accessor.go

Explicitly set the option `UseWholeCIDs` to ture, since v2 uses
multihash by default.

Enable `UseWholeCIDs` since by default CARv2 uses multihash

---

dagstore_test.go
shard.go

If the code directly writes to the channel that the `dispatcher` function is reading from, we could escape the nil channel check we've put in place in the `dispatchResult` function.

Ignore nil channels in the dispatcher

---

dagstore_control.go
dagstore_test.go

Also adds test coverage for this branch.

acquire when errored: fix result being dispatched on wrong waiter.

---

dagstore_test.go
handlers.go

This introduces a utility that DAG Store users can rely on to recover shard failures automatically, up to a maximum number of attempts. It currently does not support backoff; see #79.

add a failure handler utility to recover shards immediately.

---

dagstore.go
dagstore_async.go
dagstore_control.go
dagstore_test.go
mount/upgrader.go
shard.go

One commit per change.
This mainly redesigns the "recovery on start" solution introduced in #81, and also adds a comprehensive test.
The `RecoverOnStartPolicy` enum values have been renamed to describe the behaviour more accurately.
We no longer piggyback on the `lazy` flag, which is only relevant during registration/initialization. We introduce a `recoverOnFirstAcquire` flag instead of overloading `lazy`.
Finally, I've polished log statements, implemented an unimplemented method to avoid panicking, and made additional fixes to the upgrader.

review #81

---

dagstore.go
dagstore_async.go
dagstore_control.go
dagstore_test.go
handlers.go
mount/upgrader.go

Closes #80 .
- If we persist a shard in errored state to the datastore and then crash and restart, the shard would have forever stayed in the errored state.
- Shard Recovery should respect lazy initialization.
- Document that clients have to always actively consume from the trace and failure channels.
- Logging for all the Upgrader magic. Logging for everything.

Bug Fixes and logging

---

dagstore.go
dagstore_test.go
index/repo.go
index/repo_fs.go
mount/upgrader.go
shard_persist.go

Fixes #85, and adds two tests. One relevant to this fix, one that tests that we correctly handle missing indices on acquire (related to #83).

persist transient path + add tests.

---

dagstore.go
dagstore_control.go
dagstore_gc.go
dagstore_test.go
mount/upgrader.go
shard_persist.go

This PR closes #58.
It implements reconciliation of the transients directory, which consists of removing files that are no longer referenced by any mount, either as a complete or partial transient file.
We introduce the concept of a "partial file" in the Upgrader. The partial file is the file where a mount is being fetched into, while the fetch is in progress (cf. `.crdownload` in Chrome). This is not safe to expose as the `TransientPath`, because that would imply that it's fully functional. However, we don't want it saved in the Datastore.
I've also refactor the way that GC is triggered, so it's much neater now.

refactor GC and implement reconciliation.

---

dagstore.go
go.mod
go.sum
throttle/doc.go
throttle/throttler.go
throttle/throttler_test.go

The global fetch throttling is insufficient for the nuanced things that a mount may need doing. For example, the Lotus mount will need to unseal pieces at times. Unsealing is a long process and cannot be subject to global throttling, else a single unsealing job can be head-of-line blocking for all retrievals, including those for already-unsealed pieces.
This preserves the global throttling for indexing and fetching, but exposes the throttler so it can be embedded into Mounts that do more precise throttling (e.g. the Lotus mount, which will throttle fetches of unsealed pieces only).

expose throttler so it can be embedded in mounts.

---

dagstore.go
dagstore_async.go
dagstore_test.go
mount/upgrader_test.go
shard.go
shard_state.go

If the acquirer cancelled the context, we would never deliver the accessor and never release the shard. This was visible when testing out the new migration logic on Lotus and interrupting the `lotus dagstore initialize-all` command.

honour context cancellation on acquire.

---

go.mod
go.sum

1. The go-car dep was not released on master, but pointed to a (now revived) branch.
2. go-cid/go-multicodec were pointing to commits on master.

chore: use released deps

---

docs/design.md

Fix the rendering issue for a heading in the design doc: [before](https://github.com/filecoin-project/dagstore/blob/253211cf4b6cf2e2bfed1fb4ee07ca73baa50878/docs/design.md#car-formats) vs. [after](https://github.com/filecoin-project/dagstore/blob/9e61f02cc4dfa4ec00114b56c62d6ee30b7ba3ec/docs/design.md#car-formats)

Fix markdown heading in design doc

---

dagstore.go
dagstore_test.go
go.mod
go.sum
interface.go
invertedindex/indexer_core.go

We should be able to get an iterable index out of the dagstore so the reference provider can serve the index to the network indexer.

Api to get iterable index from the DagStore

---

dagstore_async.go

We need the Identitity cids in the Index so we can announce them to the network Indexer.

Store Identitiy cids in index

---

dagstore_control.go
dagstore_test.go

Notify caller of shard destruction

Shard Destruction

---

indexbs/indexbacked_bs.go
indexbs/indexbacked_bs_test.go

Changes to the index-backed blockstore:
1. In testing we found that blockstore.Get often fails because the block cannot be retrieved from the remote store. It is very unlikely to fail because of a corrupted index. So this PR simply returns an error immediately if an operation on the blockstore returns an error (instead of trying to re-acquire the blockstore).
2. We also found that multiple concurrent calls to AcquireShard will call mount.Fetch once each. So this PR adds a sync.Once to synchronize between concurrent calls.

index-backed blockstore - synchronize acquires

---

dagstore_control.go
dagstore_test.go

Currently, dagstore implementation only deletes the shard from in-memory map of keys. When dagstore is restarted, the shard comes back from disk.

Fix: add on-disk deletion of shards

---

go.mod
go.sum
indexbs/indexbacked_bs.go
indexbs/indexbacked_bs_test.go
testdata/testdata.go

Fixes root cause of https://github.com/filecoin-project/boost/issues/1134
In this PR I've replaced the complex locking mechanism in IndexBackedBlockstore with a striped lock, so as to eliminate the possibility of a nil blockstore.
Note that it's easiest to view changes with whitespace diff turned off:
https://github.com/filecoin-project/dagstore/pull/147/files?diff=unified&w=1

fix index backed blockstore panic by simplifying locking

---

indexbs/indexbacked_bs.go
indexbs/indexbacked_bs_test.go

Change ShardsContainingHash to ShardsContainingCid so that we can detect identity cids

change index-backed blockstore dagstore interface
